import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "../utils/api";
import { cm_serial_info, serial } from "../utils/const";
import { useContext, useEffect, useState } from "react";
import ModalSerial from "../components/ModalSerial";
import { useSerial } from "../components/ProviderSerial";
import { useDev } from "../components/ProviderDev";


const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Jacks Beans</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Authorised Route
          </h1>
          <AuthShowcase />
        </div>
        <div  className="flex flex-auto"/>
        <footer className="container flex justify-center flex-row-reverse m-10">   
        </footer>
      </main>

    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
    const { data: sessionData } = useSession();
  
    const { data: secretMessage } = api.example.getSecretMessage.useQuery(
      undefined, // no input
      { enabled: sessionData?.user !== undefined },
    );
  
    return (
      <div className="flex flex-col items-center justify-center">
        <p className="text-center text-ml text-white">
          {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
          {secretMessage && <span> - {secretMessage}</span>}
        </p>
        <button
          className="text-ml font-semibold text-white no-underline"
          onClick={sessionData ? () => void signOut() : () => void signIn()}
        >
          {sessionData ? "Log out" : "Log in"}
        </button>
      </div>
    );
  };


