import { type NextPage } from "next";
import Head from "next/head";

import {DashNavBar} from "../../components/NavBar";


const Overview: NextPage = () => {
  return (
    <>
    <Head>
    <title>Jacks Beans</title>
    <meta name="description" content="Generated by create-t3-app" />
    <link rel="icon" href="/favicon.ico" />
    </Head>
    <DashNavBar />
    <main className="flex min-h-screen flex-col items-center justify-center bg-[#232020]">
        <footer className="container flex justify-center flex-row-reverse">   
        </footer>
    </main>
    </>
  );
};





export default Overview;

