import { type NextPage } from "next";
import Head from "next/head";

import {AdminNavBar} from "../../components/NavBar";
import { api } from "../../utils/api";
import { useSession } from "next-auth/react";


const Serial: NextPage = () => {
    const { data: session } = useSession();

    const getScopes = async () => {
        console.log(session?.user)
    }

  return (
    <>
    <Head>
    <title>Jacks Beans</title>
    <meta name="description" content="Generated by create-t3-app" />
    <link rel="icon" href="/favicon.ico" />
    </Head>
    <AdminNavBar />
    <main className="flex min-h-screen flex-col items-center justify-center bg-[#232020]">

        <button className="bg-[#232020] text-white font-bold py-2 px-4 rounded" onClick={getScopes}>
            Get Scopes
        </button>
        <p>
            {session?.user?.scopeIds}
        </p>
        <footer className="container flex justify-center flex-row-reverse">   
        </footer>
    </main>
    </>
  );
};





export default Serial;

