import { type NextPage } from "next";
import Head from "next/head";

import NavBar from "../../components/NavBar";


const Admin: NextPage = () => {
    //const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
    <Head>
    <title>Jacks Beans</title>
    <meta name="description" content="Generated by create-t3-app" />
    <link rel="icon" href="/favicon.ico" />
    </Head>
    <NavBar />
    <main className="flex min-h-screen flex-col items-center justify-center bg-[#232020]">
        
        <footer className="container flex justify-center flex-row-reverse">   
        </footer>
    </main>
    </>
  );
};





export default Admin;

